### PR TITLE
fix #48

### LINKED ISSUE #48: [iOS] DisconnectAll - Collection was mutated while being enumerated
The Plugin is crashing when you try to DisconnectAll connections, it is raising the following Exception: Collection was mutated while being enumerated

### PR DESCRIPTION
**Pull request by felipekm**

### CODE REVIEW

**Comment by vinnylinck** [comment]
To be merged

**Comment by felipekm** [comment]
Awesome

**Comment by felipekm** [comment]
Do you remember why this was set as Duplicate?

**Comment by vinnylinck** [comment]
I'm pretty sure because the problem was fixed "twice". Or was about two changes for the same thing. Need to check...

-----Original Message-----

**Comment by felipekm** [comment]
:metal:

**Pull request closed without merging**
