### PR TITLE
handling JSON objects

### PR DESCRIPTION
**Pull request by felipekm**
PR for 'handle JSON objectts' issue.

### CODE REVIEW

**Comment by vinnylinck** [comment]
It works, but this still will blow up. What happens if the received information is now string and not a JSON? Once the pull request is a enhancement for JSOn only, must be accepted. On the other hand, I will add another enhancement to handle the corner cases.

Thanks for pulling up. :)

**Comment by felipekm** [comment]
Got it, but If the received data is a instance of string it will parse it with JSON.parse(), which corner cases are you actually referring for?

**Comment by vinnylinck** [comment]
Which is the logic to choose "JSON.parse" instead of "Object.toString()"? That's the point. Sometimes you have a non-json object but it can be casted through toString() method.

**Comment by felipekm** [comment]
Yup right, I've got your point.

**Pull request merged**
